language: python
dist: trusty
python:
    - "3.6"
services:
    - postgresql
env:
    - FLASK_ENV=development
    - JWT_SECRET_KEY=hhgaghhgsdhdhdd
    - DATABASE_TEST_URL=postgresql+psycopg2://test:password@localhost:5432/blog_test_db
before_script:
    - psql -c "create user test with password 'password';" -U postgres
    - psql -c 'create database blog_test_db;' -U postgres
    - psql -c 'grant all privileges on database blog_test_db to test;' -U postgres
install:
    - pip install pipenv
    - pipenv install
script:
    - python -m  unittest discover -s  src/tests
after_success:
    - coveralls
addons:
    - postgresql: "9.3"