language: python
dist: trusty
python:
    - "3.6"
services:
    - postgresql
env:
    - DATABASE_TEST_URL=postgresql+psycopg2://test:password@localhost:5432/blog_api_db
before_script:
    - psql -c 'create database blog_test_db;' -U postgres
install:
    - pip install pipenv
    - pipenv install
script:
    - pytest --cov=src --cov-config .coveragerc
after_success:
    - coveralls
addons:
    - postgresql: "9.3"